;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        elpy-nav-indent-shift-left
        ess-insert-assign
        ess-smart-comma
        indent-for-tab-command
        ivy-alt-done
        org-self-insert-command
        paredit-forward-delete
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        ivy-switch-buffer
        mouse-set-region
        org-cycle
        xref-pop-marker-stack
        ))
